import Head from "next/head";
import React from "react";
import { Inter } from "next/font/google";
import TweetEmbed from "react-tweet-embed";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Radiopancake</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={styles.main}>
        <div>
          <p className="text-center subpixel-antialiased font-mono text-lg text-center text-5xl">
            RADIOPANCAKE
          </p>
        </div>
        <div className="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal outline-block shadow-lg w-full max-w-xs rounded py-12 items-center mb-4">
          <div className="">
            <div className="flex space-x-4 px-6 pt-4 pb-2">
              <a
                href="https://sociabuzz.com/radiopancake"
                className=""
                aria-current="page"
              >
                <button className="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                  Support me
                </button>
              </a>
            </div>
          </div>
          <a className="font-bold bg-gray-900 rounded-md px-3 py-2 text-sm font-medium">
            Hellllooooo
          </a>
        </div>
        <div className="max-w-sm rounded overflow-hidden shadow-lg right-px">
          <div className="px-6 pt-4 pb-2">
            <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
              #Game devlopment
            </span>
          </div>
        </div>
        <div className="w-1/6 absolute inset-y-0 right-80 w-6 top-10 sm:invisible md:visible">
          <TweetEmbed
            className="sm:invisible md:visible"
            tweetId="1520655577726484482"
          />
        </div>
      </main>
    </>
  );
}
